team-proactive/safe-eye

about.html
index.html

확인 후 이 구역은 지워주세요.
```
해당 풀리퀘에 들어간 이모지들 [앱이름]: [이슈번호] 풀리퀘스트 설명
```
이 형태가 되어야 합니다.
예시:
```
✨🐛 [blog] (#2) 블로그 디테일 페이지 작업
```
[공식 문서 참조](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
자동, 혹은 수동으로 이슈와 풀 리퀘스트를 연결할 수 있습니다.
- 이슈 번호: #(이슈 번호)
------
(스크린샷 첨부)
- (기타 사항)
- ✨ 새로운 기능 추가
- 🐛 버그 수정
- 📚 문서 업데이트
- 🎨 코드 스타일 개선
- ⚡️ 성능 개선
- 🔧 구성 파일 변경
- ✅ 테스트 추가 / 업데이트
- 🔥 코드 또는 파일 삭제
- 🚚 파일 이동 또는 이름 변경
- 이 풀리퀘스트를 머지할 때는 스쿼시 머지를 사용해주세요.
- 스쿼시 머지 시에는 커밋 메시지 맨 끝에 있는 풀리퀘스트 번호를 `[ateam] (#10)`와 같이 앞으로 이동시켜주세요.
- 풀리퀘스트 제목 앞에 관련된 이슈 번호를 `[ateam] (#2)`와 같이 명시해주세요.

 [blog] (#2) 블로그 디테일 페이지 작업

---

config/urls.py
notice/tests.py

(#2)
- contig의 urls.py를 리팩토링하여 확장성 있게 바꾸었습니다.
- notice에 테스트 코드를 추가했습니다.

🐛✅ [notice] (#2) 샘플 테스트 코드 추가

---

.env.example
README.md
commands.sh
config/settings.py
notice/urls.py
requirements.txt

- 이슈 번호: #4
- 프론트 연동 관련한 버그를 픽스합니다.

➕🐛✨ [blog] (#4) 블로그 디테일 페이지 작업

---

notice/serializers.py

- #4 
- 시리얼라이저에 id 필드가 추가되지 않아서 안오던 것을 해결하는 패치입니다.
- 
.

🐛 [notice] (#4) add id field on serializers

---

.gitignore
README.md

- 이슈 번호: #7 
- 테스트 커밋을 적용하는 풀리퀘
.

📝 [readme] (#7) 블로그 디테일 페이지 작업

---

config/settings.py
config/urls.py
utils/admin.py
utils/apps.py
utils/mixins.py
utils/models.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #19 
- 다른 앱들이 공통적으로 사용할 수 있는 기능을 제공
-

✨ [utils] (#19) utils app 제작

---

utils/fixtures/initial_data.json
utils/mixins.py
utils/serializers.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #19 
- DRF 적용 코드로 수정
- serializers.py 추가, mixins.py 수정
- tests.py 추가, initial_data.json 파일 추가

✅🎨 [utils] (#19) serializers.py, tests.py 추가 및 DRF 적용 코드로 수정

---

utils/fixtures/initial_data.json
utils/models.py
utils/serializers.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #19 
- 페이지네이션 추가.
- views.py 내 class ViewSet 으로 수정.
- 오류 원인이던 tag_id 삭제, id로 사용.
- 없음.

🐛 🎨 [utils] (#19) views.py 페이지네이션 추가, ViewSet 으로 변경, tag_id 오류 수정

---

accounts/models.py
accounts/serializers.py
accounts/tests.py
accounts/urls.py
accounts/views.py
config/settings.py

- 이슈 번호: #24 
- User 모델과 연결된 status 모델을 정의하고, status 필드는 외래키로 설정
- User 모델 생성 시 기본 status를 자동 할당하는 로직 추가
- ViewSet을 사용하여 사용자 관련 API 엔드포인트 구현 (회원가입, 로그인, 사용자 정보 조회/수정 등)
- config의 settings.py 파일에 AUTH_USER_MODEL 설정 추가
- 없습니다. :D

✨📚[accounts] (#24) accounts 기능 추가 및 config 파일에 setting.py 변경

---

accounts/admin.py
accounts/apps.py
accounts/models.py
accounts/serializers.py
accounts/tests.py
accounts/urls.py
accounts/views.py
commands.sh
config/settings.py
config/urls.py
requirements.txt

- 이슈 번호: #24 
- 어카운트 앱을 새로 제작합니다.
- jwt 라이브러리를 추가합니다.
- 관련하여 commands.sh에 pip를 requirements.txt의 내용에 따라 업데이트 하는 커맨드
-> upgrede_pip 를 추가합니다.
```
./commands.sh
upgrede_pip
```
이 풀리퀘는 config의 settings.py를 수정하므로 관련 사항을 로컬에서 업데이트 받을때 주의해주세요.
------
(스크린샷 첨부)
- (기타 사항)
- ✨ 새로운 기능 추가
- 🐛 버그 수정
- 📚 문서 업데이트
- 🎨 코드 스타일 개선
- ⚡️ 성능 개선
- 🔧 구성 파일 변경
- ✅ 테스트 추가 / 업데이트
- 🔥 코드 또는 파일 삭제
- 🚚 파일 이동 또는 이름 변경
- 이 풀리퀘스트를 머지할 때는 스쿼시 머지를 사용해주세요.
- 스쿼시 머지 시에는 커밋 메시지 맨 끝에 있는 풀리퀘스트 번호를 `[ateam] (#10)`와 같이 앞으로 이동시켜주세요.
- 풀리퀘스트 제목 앞에 관련된 이슈 번호를 `[ateam] (#2)`와 같이 명시해주세요.

✨🐛 [accounts] {#24) 어카운트 앱 작성

---

commands.sh
config/settings.py
config/urls.py
test/reset_database_schemes.py
utils/fixtures/initial_data.json

- 이슈 번호: #35 
- mock_data 추가, settings.py, urls.py 수정
없음

🐛 [utils] fix acoounts의 변경에 따라 utils 업데이트

---

utils/mixins.py
utils/models.py
utils/serializers.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #37 
- accounts 앱 추가되면서 user 와 superuser 구분됨에 따라 utils 앱 내 권한 관련 부분 수정.
- utils 앱 mixins.py 파일 내 IsAuthorOrReadOnly 함수 개선.
- mixins.py 수정에 맞춰 tests.py 수정.
- Black Formatter 적용 안된 utils 앱 내 파일 적용 후 같이 커밋.
없음

🐛 utils 앱 mixins.py 내 함수 개선

---

utils/mixins.py
utils/models.py
utils/serializers.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #37 
- accounts 앱 추가되면서 user 와 superuser 구분됨.
- utils 앱 내 mixins.py 파일 내 IsAuthorOrReadOnly 함수 개선. superuser 쓰기 권한 부여.
현재 local 과 포크 떴던 제 계정의 레포지토리에는 적용이 되어 있어서 upstream 에도 
반영하기 위해 pull request 만들었습니다. 참고해주세요.

🐛 [utils] (#37) utils 앱 개선

---

media/models.py
media/serializers.py
media/tests.py
media/urls.py
media/views.py
requirements.txt

- [*] 커밋 메시지가 가이드라인을 준수했습니다.
- [*] 플 리퀘스트에 이슈가 링크되어 있습니다.
- [*] 변경 사항에 대한 테스트가 추가되었습니다.
- [*] 관련 문서가 추가 / 업데이트되었습니다.
- 이슈 번호: #25 
✨ 기존 media 앱의 파일들을 수정하여 AI 모델을 통합할 수 있습니다. 주요 변경 사항은 다음과 같습니다:
✨models.py에 AI 모델 파일 경로를 저장할 필드를 추가합니다.
✨views.py에서 AI 모델을 불러오고 예측 로직을 추가합니다.
✨serializers.py에 AI 모델 필드를 추가합니다.
✨urls.py에 AI 모델 예측을 위한 엔드포인트를 추가합니다.
✨tests.py에 AI 모델 예측 테스트 케이스를 추가합니다.
📚 제공받은 AI모델에서 요구하는 라이브러리 몇개를 설치했습니다. requirements.txt에추가하면 될까요?
✅ 특정 라이브러리에서 https://visualstudio.microsoft.com/ko/visual-cpp-build-tools/ 선행설치를 요구합니다. 로컬뿐아니라 깃헙에도 연결하려면 팀장님의 조언이 필요할것같습니다.

✨🐛 [blog] (#25) 미디어 앱 제작 작업

---

alarm/admin.py
alarm/apps.py
alarm/models.py
alarm/serializers.py
alarm/tests.py
alarm/urls.py
alarm/views.py
config/settings.py
config/urls.py
utils/mixins.py

- 이슈 번호: #22 
- alarm app 제작
- settings.py, urls.py 에 alarm 앱 추가
- utils app 의 mixins.py 에 IsAuthorOrReadOnly 함수 수정.
없음

✨🐛 [alarm] (#22) alarm app 제작, 설정파일 alarm 추가, utils/mixins.py 개선

---

accounts/serializers.py
accounts/views.py

- 이슈 번호: #35 
- 프론트에 연결하면서 JWT를 위해 누락된 부분이 있어 업데이트 합니다.
- 회원가입은 변경 없이 연결이 잘 됩니다.
- accounts app을 작업하지 않았다면 괜찮습니다.

✨ [accounts] (#35) 로그인 기능 추가

---

accounts/admin.py
accounts/tests.py

확인 후 이 구역은 지워주세요.
```
해당 풀리퀘에 들어간 이모지들 [앱이름]: [이슈번호] 풀리퀘스트 설명
```
이 형태가 되어야 합니다.
예시:
```
✨🐛 [blog] (#2) 블로그 디테일 페이지 작업
```
[공식 문서 참조](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
자동, 혹은 수동으로 이슈와 풀 리퀘스트를 연결할 수 있습니다.
- 이슈 번호: #(이슈 번호)
------
(스크린샷 첨부)
- (기타 사항)
- ✨ 새로운 기능 추가
- 🐛 버그 수정
- 📚 문서 업데이트
- 🎨 코드 스타일 개선
- ⚡️ 성능 개선
- 🔧 구성 파일 변경
- ✅ 테스트 추가 / 업데이트
- 🔥 코드 또는 파일 삭제
- 🚚 파일 이동 또는 이름 변경
- 이 풀리퀘스트를 머지할 때는 스쿼시 머지를 사용해주세요.
- 스쿼시 머지 시에는 커밋 메시지 맨 끝에 있는 풀리퀘스트 번호를 `[ateam] (#10)`와 같이 앞으로 이동시켜주세요.
- 풀리퀘스트 제목 앞에 관련된 이슈 번호를 `[ateam] (#2)`와 같이 명시해주세요.

[accounts] (#47) ✨feat: accounts 추가

---

.gitignore
accounts/admin.py
accounts/fixtures/initial_data.json
accounts/models.py
accounts/permissions.py
accounts/serializers.py
accounts/tests.py
accounts/urls.py
accounts/views.py
config/settings.py

- 이슈 번호: #35 
- accounts에 고도화 기능으로 중첩된 유저구조 추가
- superuser를 추가
- 일반 유저 생성시 어드민 유저의 토큰이 필요하게 개선
- accounts 앱을 작업하고 있었다면 문제가 생길 수 있습니다. 작업을 취소하고 풀을 받아주셔야 해요.

✨🙈✅ [accounts] (#35) 유저 카스케이딩 및 테스트 코드

---

alarm/models.py
alarm/serializers.py
alarm/urls.py
alarm/views.py
utils/mixins.py
utils/serializers.py

- 이슈 번호: #52 
- alarm_type 필드를 별도의 모델로 분리
- Alarm 모델의 user 필드를 CustomUser 모델의 외래 키로 설정
- mixins.py 내 IsAuthorOrReadOnly 클래스 수정
- 
없음

[alarm] [utils] (#52) alarm 앱 고도화 작업, utils 앱 mixins.py 수정

---

alarm/models.py
alarm/serializers.py
alarm/urls.py
alarm/views.py
utils/mixins.py
utils/serializers.py

- 이슈 번호: #52 
- alarm_type 필드를 별도의 모델로 분리
- Alarm 모델의 user 필드를 CustomUser 모델의 외래 키로 설정
- mixins.py 내 IsAuthorOrReadOnly 클래스 수정
없습니다.

[alarm] [utils] (#55) (#52) alarm 앱 고도화 작업, utils 앱 mixins.py 수정

---

utils/mixins.py
utils/tests.py

- 이슈 번호: #56 
- admin 추가로 utils앱 내 IsAuthorOrReadOnly 클래스 수정
- accounts 앱이 개선되면서 기존의 tests.py 실행오류 발생하여 수정
없음

🐛 [utils] (#56) accounts 앱 개선에 따른 utils앱 mixins.py, tests.py 수정

---

alarm/models.py
alarm/serializers.py
alarm/tests.py
alarm/urls.py
alarm/views.py

- 이슈 번호: #57 
- AlarmType 클래스 분리
- AlarmType 클래스 객체 생성시 중첩 데이터 유효성 검사 추가
- AlarmSerializer 클래스 log_format 필드 추가
- AlarmViewSet 클래스 receive_alarm_data 함수 추가
- 없음

 🐛🚀 [alarm] (#57) alarm 앱 개선 alarmType 클래스 분리 및 코드 개선

---

accounts/admin.py
accounts/forms.py
accounts/models.py
accounts/permissions.py
accounts/serializers.py
accounts/urls.py
accounts/views.py
config/settings.py
config/urls.py

- 이슈 번호: #35 
- accounts에 아이디 없이 헤더에 포함된 토큰 정보를 읽어서 사용자 정보를 가져오는 로직을 추가했습니다.

✨🐛 [accounts] (#35) 토큰으로 사용자 정보를 가져오는 api 추가

---

alarm/models.py
alarm/serializers.py
alarm/tests.py
alarm/urls.py
alarm/views.py
config/settings.py
config/urls.py
utils/mixins.py
utils/models.py
utils/serializers.py
utils/tests.py
utils/urls.py
utils/views.py

- 이슈 번호: #69 
- alarm 앱, utils 앱 doc string 추가
- settings 내 urls.py path 오류 수정
- utils 앱 serializers.py 필요 없는 코드 삭제
- 없음

🐛 📝 (#69) alarm 앱, utils 앱 doc string 추가, urls.py 수정

---

chat/admin.py
chat/apps.py
chat/models.py
chat/serializers.py
chat/tests.py
chat/urls.py
chat/views.py

- 이슈 번호: #68 
add chat doc stirng
없습니다!

📝 feat: add chat doc stirng

---

accounts/apps.py
accounts/forms.py
accounts/models.py
accounts/permissions.py
accounts/serializers.py
accounts/tests.py
accounts/views.py

- 이슈 번호: #73
add accounts doc string
없습니다!

📝 feat: add accounts doc string

---

accounts/admin.py
accounts/urls.py

- 이슈 번호: #75 
complement accounts doc string
없습니다

📝 feat: complement accounts doc string
